docollective/accounts/urls.py
from django.urls import path
from .views import (signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate, graphique, addresult, profile_eleve,
    multiplication, jeu ,verificationReponse, modal, soustraction, choixOperation, addition, multiplicationTable)

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('graphique/', graphique, name="graphique"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete"),
    path('multiplication/', multiplication, name="multiplication"),

    path('saveresult/', addresult, name="addresult"),
    #path('getdata/', getdata, name="getdata"),
    path('profile_eleve/', profile_eleve, name="profile_eleve"),
    #path('test_htmx/', test_htmx, name="test_htmx"),
    path('jeu/', jeu, name="jeu"),
    path('multiplicationTable/', multiplicationTable, name="multiplicationTable"),
    path('soustraction/', soustraction, name="soustraction"),
    path('addition/', addition, name="addition"),
    path('choixOperation/', choixOperation, name="choixOperation"),
    path('verificationReponse/', verificationReponse, name="verificationReponse"),
    path('modal/', modal, name="modal")
]

docollective/docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

docollective/sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

docollective/accounts/models.py
import iso3166
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

from shop.models import SIZES, Color

# TYPE_USER = [("h", "Homme"), ("f", "Femme"), ("nr", "Non renseigné")]
TYPE_USER = [("h", "Homme"), ("f", "Femme")]


class ExChangerManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password, **kwargs):
        if not email:
            raise ValueError("email obligatoire")
        user = self.model(email=self.normalize_email(email), username=username, first_name=first_name,
                          last_name=last_name, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, first_name, last_name, password, **kwargs):
        user = self.create_user(email, username, first_name, last_name, password, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        return user


class ExChanger(AbstractUser):
    email = models.EmailField(unique=True)
    type = models.CharField(max_length=10, verbose_name="Sexe", choices=TYPE_USER)

    score_multiplication = models.IntegerField(default=0)
    score_addition = models.IntegerField(default=0)
    score_soustraction = models.IntegerField(default=0)
    score_division = models.IntegerField(default=0)

    #tablemultiplication_Niveau = models.IntegerField(default=1) #CREATION DE L'ATTRIBUT

    duree_connexion = models.IntegerField(default=0)

    a = models.IntegerField(default=0)
    b = models.IntegerField(default=0)
    answer = models.IntegerField(default=0)
    reponseEleve = models.FloatField(default=0)

    url = models.CharField(max_length=100, default=0)

    nombreQuestions = models.IntegerField(default=0)
    reponsesJustes = models.IntegerField(default=0)
    reponsesFausses = models.IntegerField(default=0)
    reponsesJustesPourcentage = models.FloatField(default=0)
    reponsesFaussesPourcentage = models.FloatField(default=0)

    tempsMoyenCentieme = models.FloatField(default=0)
    horaire1 = models.FloatField(default=0)
    #horaire2 = models.FloatField(default=0)
    Duree = models.FloatField(default=0)



    REQUIRED_FIELDS = ["username", "first_name", "last_name"]
    USERNAME_FIELD = "email"

    objects = ExChangerManager()

class Score(models.Model):
    user = models.OneToOneField(ExChanger, on_delete=models.CASCADE)
    multiplication = models.IntegerField(default=0)
    multiplicationNiveau = models.IntegerField(default=0)
    multiplicationALaSuite = models.IntegerField(default=0)
    multiplicationsFaussesALaSuite = models.IntegerField(default=0)


class Points(models.Model):
    user = models.OneToOneField(ExChanger, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    score1 = models.IntegerField(default=0)
    score2 = models.IntegerField(default=0)
    score3 = models.IntegerField(default=0)
    score4 = models.IntegerField(default=0)
    score5 = models.IntegerField(default=0)


class Meta:
    verbose_name="Point"

def __str__(self):
    return f"{self.user.username} à pour score : {self.score}"

class REPONSE(models.Model):
    name = models.CharField(max_length=255)

docollective/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, forms
from captcha.fields import ReCaptchaField


class ExChangerSignupForm(UserCreationForm):
    captcha = ReCaptchaField()

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "first_name", "last_name", "type"]

docollective/accounts/views/password.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


class ExchangerChangePassword(PasswordChangeView):
    template_name = "password/change-form.html"
    success_url = reverse_lazy("accounts:change-done")


class ExchangerPasswordDone(PasswordChangeDoneView):
    template_name = "password/change-done.html"


class ExchangerResetPassword(PasswordResetView):
    template_name = "password/reset.html"
    success_url = reverse_lazy("accounts:reset-done")
    email_template_name = "password/reset-email.html"


class ExchangerResetDone(PasswordResetDoneView):
    template_name = "password/reset-done.html"


class ExchangerResetConfirm(PasswordResetConfirmView):
    template_name = "password/reset-confirm.html"
    success_url = reverse_lazy("accounts:reset-complete")


class ExchangerResetComplete(PasswordResetCompleteView):
    template_name = "password/reset-complete.html"

docollective/accounts/views/user.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from accounts.forms import ExChangerSignupForm

from verify_email.email_handler import send_verification_email

from accounts.models import Points

from random import *

from accounts.models import REPONSE

from time import time

from ..themes.Addition import Addition
from ..themes.TablesDeMultiplication import TablesDeMultiplication
from ..themes.Soustraction import Soustraction
from ..themes.ChoixOperation import ChoixOperation
from ..themes.VerificationReponse import VerificationReponse

from accounts.models import Score



def signup(request):
    if request.method == "POST":
        form = ExChangerSignupForm(request.POST)
        if form.is_valid():
            inactive_user = send_verification_email(request, form)
            Score.objects.create(user=inactive_user)
            return redirect("index")
        # Sans le else j'ai un formulaire vide si pas valide
    else:
        form = ExChangerSignupForm()
    return render(request, "accounts/signup.html", context={"form": form})


class ExChangerLogin(LoginView):
    template_name = "accounts/login.html"
    next_page = reverse_lazy("index")


def exchanger_logout(request):
    logout(request)
    return redirect("index")


@login_required
def exchanger_profile(request):
    user = request.user
    try:
        default_adresse = user.adresses.get(user=user, default=True)
    except ObjectDoesNotExist:
        default_adresse = None

    adresses = user.adresses.filter(user=user, default=False)

    return render(request, "accounts/profile.html", context={"user": user,
                                                             "default_adresse": default_adresse,
                                                             "adresses": adresses})

@login_required
def profile_eleve(request):
    user = request.user
    return render(request, "accounts/profile_eleve.html", context={"user": user})

class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = "accounts/update-profile.html"
    fields = ["email", "username", "first_name", "last_name"]
    success_url = reverse_lazy("accounts:profile_eleve")


def default_address_view(request, pk):
    user = request.user

    # current_address = user.adresses.get(user=user, default=True)
    # current_address.default = False
    # current_address.save()
    #
    # new_address = user.adresses.get(pk=pk)
    # new_address.default = True
    # new_address.save()
    # Mettre à jour l'adresse actuelle par défaut
    user.adresses.filter(default=True).update(default=False)

    # Définir la nouvelle adresse comme adresse par défaut
    updated_rows = user.adresses.filter(pk=pk).update(default=True)

    # Vérifier si l'adresse avec `pk=pk` a été mise à jour
    if not updated_rows:
        # Gérer l'erreur ici, par exemple en retournant une réponse d'erreur
        return HttpResponse("Adresse non trouvée", status=404)

    if request.GET.get("redirect") == "validate":
        return redirect("shop:address-choice")

    return redirect("accounts:profile")



#Test pour afficher le graphique
@login_required
def graphique(request):
    user = request.user
    return render(request, "accounts/graphique.html", context={"user": user})

@login_required
def multiplication(request):
    user = request.user
    return render(request, "accounts/multiplication.html", context={"user": user})

@login_required
def addresult(request):
    user = request.user
    tempsMoyenCentieme = request.POST.get('tempsMoyenCentieme')
    user.tempsMoyenCentieme = tempsMoyenCentieme
    user.save(update_fields=['tempsMoyenCentieme'])
    return redirect("accounts:modal")

@login_required
def jeu(request):
    user = request.user
    user.nombreQuestions = 0
    user.reponsesJustes = 0
    user.reponsesFausses = 0
    user.reponsesJustesPourcentage = 0
    user.reponsesFaussesPourcentage = 0
    user.Duree = 0
    user.save(update_fields=['nombreQuestions', 'reponsesJustes', 'reponsesFausses', 'reponsesJustesPourcentage', 'reponsesFaussesPourcentage', 'Duree'])
    # INITIALISATION DES QUESTIONS A LA SUITE
    user.score.multiplicationALaSuite = 0
    user.score.save(update_fields=['multiplicationALaSuite'])

    if request.method == "POST":
        if form.is_valid():
            print(form.cleaned_data)
    return render(request, "accounts/jeu.html", context={"user": user})

@login_required
def choixOperation(request):
    user = request.user
   # tableauOperation = ["accounts:test_htmx","accounts:soustraction"]
    #indice = randint(0, 1)
    #url_operation = tableauOperation[indice]
    #return render(request, "accounts/choixOperation.html", context={"url_operation": url_operation })
    url, a, b, answer = ChoixOperation(user)
    return render(request, url, context={"user": user, "a": a, "b": b, "answer": answer})



@login_required
def multiplicationTable(request):
    user = request.user
    #user = request
    a,b,answer = TablesDeMultiplication(user)
    #return render(request, "accounts/multiplicationTable.html", context={"user": user, "a": a, "b": b, "answer":answer})
    return render(request, "accounts/multiplicationTableAlenvers.html", context={"user": user, "a": a, "b": b, "answer": answer})




@login_required
def soustraction(request):
    user = request.user
    a,b = Soustraction(request.user)
    return render(request, "accounts/soustraction.html", context={"user": user, "a": a, "b": b})

def addition(request):
    user = request.user
    a,b = Addition(request.user)
    return render(request, "accounts/addition.html", context={"user": user, "a": a, "b": b})

@login_required
def verificationReponse(request):
    user = request.user
    user.reponseEleve = int(request.POST.get('name'))
    user.save(update_fields=['reponseEleve'])
    return HttpResponse(VerificationReponse(user))

    """
    answer = request.user.answer

    user.nombreQuestions +=1
    user.save(update_fields=['nombreQuestions'])

    horaire2 = time()

    duree = horaire2 - request.user.horaire1
    request.user.Duree = request.user.Duree + duree
    user.save(update_fields=['Duree'])

    html_response_nbre_questions ="<h6 id='hid_nombreQuestions'>Nombre de Question(s) : %s</h6>"

    if reponse == request.user.answer:
        user.reponsesJustes +=1
        user.save(update_fields=['reponsesJustes'])
        user.reponsesJustesPourcentage = round((user.reponsesJustes / user.nombreQuestions) * 100, 1);
        user.reponsesFaussesPourcentage = round((user.reponsesFausses / user.nombreQuestions) * 100, 1);
        user.save(update_fields=['reponsesJustesPourcentage', 'reponsesFaussesPourcentage'])

        if user.score.multiplication == 1:
            user.score.multiplicationALaSuite +=1
            user.score.save(update_fields=['multiplicationALaSuite'])
            if user.score.multiplicationALaSuite == 5:
                if user.score.multiplicationNiveau != 4:
                    user.score.multiplicationNiveau +=1
                    user.score.save(update_fields=['multiplicationNiveau'])
                    user.score.multiplication = 0
                    user.score.save(update_fields=['multiplication'])



        html_response = ("<h2>Bravo, c'est la bonne réponse</h2><input class='form-control-lg w-100 h-100 vrai' type='number' name='name' value='' disabled  style='font-size:30px; text-align:center;' id='hid_inp' placeholder=%s>" % answer)
        html_response_reponses_justes ="<h6 id='hid_resultatsJustes'>Réponse(s) Juste(s) : %s </h6>"
        return HttpResponse(html_response + html_response_reponses_justes % user.reponsesJustes + html_response_nbre_questions % user.nombreQuestions)

    else :
        user.reponsesFausses +=1
        user.save(update_fields=['reponsesFausses'])
        user.reponsesJustesPourcentage = round((user.reponsesJustes / user.nombreQuestions) * 100, 1);
        user.reponsesFaussesPourcentage = round((user.reponsesFausses / user.nombreQuestions) * 100, 1);
        user.save(update_fields=['reponsesJustesPourcentage', 'reponsesFaussesPourcentage'])

        if user.score.multiplication == 1:
            user.score.multiplicationALaSuite = 0
            user.score.save(update_fields=['multiplicationALaSuite'])
            user.score.multiplication = 0
            user.score.save(update_fields=['multiplication'])

        html_response1 = "<h2 class='text-danger'>Faux, la bonne réponse est %s</h2>"
        html_response2 = "<input class='form-control-lg w-100 h-100 faux' type='number' name='name' value='' disabled style='font-size:30px; text-align:center;' id='hid_inp' placeholder=%s>"
        html_response_reponses_fausses = "<h6 id='hid_resultatsFaux'> Réponse(s) Fausse(s) : %s </h6>"
        return HttpResponse(html_response1 % answer + html_response2 % reponse + html_response_reponses_fausses % user.reponsesFausses + html_response_nbre_questions % user.nombreQuestions)
    """

@login_required
def modal(request):
    user = request.user
    dureeMoyenDuJeu = round(request.user.Duree/request.user.nombreQuestions,1)
    return render(request, "accounts/modal.html", context={ "user": user, "dureeMoyenDuJeu":dureeMoyenDuJeu})

docollective/accounts/templates/accounts/jeu.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Multiplication{% endblock %}

{% block body %}

<!--<!DOCTYPE html>
<html lang="fr">-->
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Multiplication Quiz WebApp</title>
	<script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
	<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>
	<link rel="stylesheet" href="{% static 'css/stylecalc.css' %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>

<!-- A RAJOUTER SUR TOUTES LES PAGES HTML -->
<section class="py-2">
    <div class="container px-4 px-lg-5 mt-5">
<!-- A RAJOUTER SUR TOUTES LES PAGES HTML -->

	<div class="text-center">
		<button onclick="active() ; changerCouleurEtFocus() ; demarrerTime()" class="form-control btn btn-primary mb-1" id="hid_demarrer" type="button"
			hx-target="#hid_bloc0"
			hx-get="{% url 'accounts:choixOperation' %}"
			hx-trigger="click">
		Démarrer</button>
	</div>


		<div class="container">
			<div id="form">
				<div class="row">
					<div class="col-4 pt-3 text-start" >
						<h6 id="hid_nombreQuestions">Nombre de Question(s) : 0 </h6>
					</div>
					<div class="col-4 pt-3 text-center">
						<h6 id="hid_resultatsJustes">Réponse(s) Juste(s) : 0 </h6>
					</div>
					<div class="col-4 pt-3 text-end">
						<h6  id="hid_resultatsFaux">Réponse(s) Fausse(s) : 0 </h6>
					</div>
				</div>
			</div>
		</div>

		<div class="col-12 p-2"></div>

		<!-- Formulaire -->
			<div id="hid_container" class="row align-items-center border border-primary rounded bg-light bg-gradient p-5 shadow">
				<div class="row">
					<div class="col-lg-8 col-md-12 col-sm 12">
						<form>
								<div id="hid_bloc0" class="text-center align-self-center mt-1">
									<h1 id="nombreMasque" class="fw-bold display-1 col align-self-center"></h1>
								</div>
						</form>
					</div>
					<div class="col-lg-4 col-md-12 col-sm 12">
						<form method="POST" hx-post="{% url 'accounts:verificationReponse' %}" hx-target="#hid_commentaire" hx-select-oob="#hid_inp, hid_nombreQuestions, hid_resultatsJustes, hid_resultatsFaux" hx-swap="innerHtml" hx-disabled-elt="#hid_btn_valider">
						{% csrf_token %}
							<div class="form-row d-flex ">
								<div class="col align-items-center mx-2">
									<input class="form-control w-100 h-100" type="number" name="name" id="hid_inp" autofocus style="font-size:30px; text-align:center;" value="">
								<!--	<input class="form-control-lg w-100 h-50" type="number" name="name2" id="hid_inp2" style="font-size:30px; text-align:center;" value="">-->
								</div>

								<!--<div class="form-group row">
								  <div class="col-xs-1">
									<input class="form-control" type="number" name="name" id="hid_inp" autofocus style="font-size:30px; text-align:center;" value="">
								  </div>
								  <div class="col-xs-1">
									<input class="form-control" type="number" name="name2" id="hid_inp2" style="font-size:30px; text-align:center;" value="">
								  </div>
								</div>-->









								<div class="col align-items-center mx-2">
									<!--<button class="form-control btn btn-primary" id="hid_btn_valider" onclick="valid()">Valider</button>-->
									<button class="form-control btn btn-primary" id="hid_btn_valider" onclick="maz() ; stop()">Valider</button>
									<div style="display:block" id="hid_div1">
										<!--<button onclick="continuer()" class="form-control mt-2 btn btn-primary" id="hid_btn2" type="button" hx-target="#hid_bloc0" hx-get="{% url 'accounts:choixOperation' %}" hx-trigger="click">
										Continuer</button>-->
										<button onclick="activeContinuer() ; changerCouleurEtFocus() ; demarrerTime() ; raz()" class="form-control mt-2 btn btn-primary" id="hid_btn2" type="button" hx-target="#hid_bloc0" hx-get="{% url 'accounts:choixOperation' %}" hx-trigger="click">
										Continuer</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>


		<p class="text-left align-bottom mt-3 text-secondary">Temps : <span id="hid_timer">0</span> s</p>


	<!-- LIGNE COMMENTAIRE ET APPEL DE MODAL HTMX-->


					<form method="POST" hx-post="{% url 'accounts:addresult' %}">
						{% csrf_token %}
							<div class="row">
								<div class="col-3 text-left align-self-center">
									<h1 type="number" id='html_tempsMoyenCentieme' name="tempsMoyenCentieme"></h1>
								</div>

								<div class="col-6 text-left align-self-center" >
									<h2 class="align-self-top text-success" id="hid_commentaire" style="text-align:center"></h2>
								</div>

								<div class="col-3 text-right align-self-right">
									<button
										type="submit"
										hx-get="{% url 'accounts:modal' %}"
										hx-target="#modals-here"
										hx-trigger="click"
										data-bs-toggle="modal"
										data-bs-target="#modals-here"
										class="btn btn-primary"
										id="hid_enregistrer"
										>Enregistrer et quitter
									</button>

									<div id="modals-here"
										class="modal modal-blur fade"
										style="display: none"
										aria-hidden="false"
										tabindex="-1">
										<div class="modal-dialog modal-lg modal-dialog-centered" role="document">
											<div class="modal-content"></div>
										</div>
									</div>
								</div>
							</div>
					</form>
			</div>
		</div>



<!--	<form method="post" action="{% url 'accounts:addresult' %}">
		{% csrf_token %}
		<input type="number" id='html_tempsMoyenCentieme' name="tempsMoyenCentieme">
	</form>
-->


	<!-- Fenêtre modal popup -->
	<!--<div class="modal fade" data-backdrop="static" id="modalWindow">
	  <div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
		  <div class="modal-header">
			<h5 class="modal-title">Enregistrement en cours</h5>
		  </div>
		  <div class="modal-body">
			  <p id="hid_modale_nombre_questions">Nombre de question(s) :</p>
			  <p class="indentation" id="hid_modale_resultats_justes"> Réponses justes.</p>
			  <p class="indentation" id="hid_modale_resultats_faux"> de réponses fausses.</p>
			  <p class="indentation" id="hid_modale_temps"> Temps moyen</p>
		  </div>
		  <div class="modal-footer">
				<form method="post" action="{% url 'accounts:addresult' %}">
					{% csrf_token %}
					<input type="hidden" type="number" id="hid_score_multiplication" name="score_multiplication" placeholder="score">
					<input type="hidden" type="number" id="hid_score_addition" name="score_addition" placeholder="score">
					<input type="hidden" type="number" id="hid_score_soustraction" name="score_soustraction" placeholder="score">
					<input type="hidden" type="number" id="hid_score_division" name="score_division" placeholder="score">
					<input type="hidden" type="number" id="hid_tablemultiplication_Niveau" name="tablemultiplication_Niveau" placeholder="score">

					<input type="hidden" type="number" id="hid_duree_connexion" name="duree_connexion" placeholder="score">
					<input type="submit" value="Valider" class="btn btn-primary">
				</form>
		  </div>
		</div>
	  </div>
	</div>-->





	 <div class="card mx-auto mb-5" style="width: 18rem;">
                    <div class="card-header"> Profil </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Email : {{ user.email }}</li>
                        <li class="list-group-item">Pseudo : {{ user.username }}</li>
                        <li class="list-group-item">Nom : {{ user.first_name }}</li>
                        <li class="list-group-item">Prénom : {{ user.last_name }}</li>
                     	<li class="list-group-item">score_multiplication : {{ user.score_multiplication }}</li>
						<li class="list-group-item">score_addition : {{ user.score_addition }}</li>
						<li class="list-group-item">score_soustraction : {{ user.score_soustraction }}</li>
						<li class="list-group-item">score_division : {{ user.score_division }}</li>
						<li class="list-group-item">Durée de connexion : {{ user.duree_connexion }}</li>
						<li id="hid_niveau" class="list-group-item">{{ user.tablemultiplication_Niveau }}</li>
					</ul>
	 </div>

	<!--<p id="hid_espace" hidden>&nbsp;&nbsp;&nbsp;</p>-->

	<!-- PLAYER BLEU-->
	<!--<script src="https://unpkg.com/@lottiefiles/lottie-player@0.3.0/dist/lottie-player.js"></script>-->

	<!--FICHIER EMBARQUE
	<script src="{% static 'js/lottie_player.js' %}"></script>-->


	<!-- PLAYER VERT-->
	<!--<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>-->




	<!--<dotlottie-player src="{% static 'lottie/Addition1.lottie.json' %}"
					  background="transparent"
					  speed="1"
					  style="width: 20%;
					  		height: 20%;

         				 	--lottie-player-seeker-track-color: #5e9efb;
          				 	--lottie-player-seeker-thumb-color: #5e9efb;
          				 	--lottie-player-toolbar-icon-color: #5e9efb;

          				 	--lottie-player-seeker-background: #5e9efb;
        			  		"
					  direction="1"
					  playMode="normal"
					  controls
					  hover></dotlottie-player>-->

<!--DERNIERE VERSION DE LOTTIE QUI FONCTIONNE
	<lottie-player
        id="playerHandler"
        src="{% static 'lottie/Addition1.lottie.json' %}"
        background="transparent"
		speed="1"
		style="width: 50%;
			   height: 50%;
			   --lottie-player-seeker-track-color: #D3D3D3;
          	   --lottie-player-seeker-thumb-color: #5e9efb;
        "
        direction="1"
		playMode="normal"
        controls></lottie-player> -->


	<script src="{% static 'js/multiplication.js' %}"></script>
	<script>lancement()</script>
	<!--<script src="{% static 'js/progressbar.js' %}"></script>-->


<!-- A RAJOUTER SUR TOUTES LES PAGES HTML -->
	</div>
</section>
<!-- A RAJOUTER SUR TOUTES LES PAGES-->

</body>
</html>
{% endblock %}