docollective/accounts/urls.py
from django.urls import path
from .views import (signup, ExChangerLogin, exchanger_logout, exchanger_profile, default_address_view, \
    ExchangerChangePassword, ExchangerPasswordDone, ExchangerResetPassword, ExchangerResetDone, ExchangerResetConfirm, \
    ExchangerResetComplete, ProfileUpdate, graphique, addresult, profile_eleve,
    multiplication, jeu ,verificationReponse, modal, soustraction, choixOperation, addition, multiplicationTable)

app_name = "accounts"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('login/', ExChangerLogin.as_view(), name="login"),
    path('logout/', exchanger_logout, name="logout"),
    path('profile/', exchanger_profile, name="profile"),
    path('graphique/', graphique, name="graphique"),
    path('profile-update/<int:pk>', ProfileUpdate.as_view(), name="profile-update"),
    path('default_adresse/<int:pk>/', default_address_view, name="default_address"),
    path('change-password/', ExchangerChangePassword.as_view(), name="change-password"),
    path('change-done/', ExchangerPasswordDone.as_view(), name="change-done"),
    path('reset/', ExchangerResetPassword.as_view(), name="reset"),
    path('reset-done/', ExchangerResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ExchangerResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ExchangerResetComplete.as_view(), name="reset-complete"),
    path('multiplication/', multiplication, name="multiplication"),

    path('saveresult/', addresult, name="addresult"),
    #path('getdata/', getdata, name="getdata"),
    path('profile_eleve/', profile_eleve, name="profile_eleve"),
    #path('test_htmx/', test_htmx, name="test_htmx"),
    path('jeu/', jeu, name="jeu"),
    path('multiplicationTable/', multiplicationTable, name="multiplicationTable"),
    path('soustraction/', soustraction, name="soustraction"),
    path('addition/', addition, name="addition"),
    path('choixOperation/', choixOperation, name="choixOperation"),
    path('verificationReponse/', verificationReponse, name="verificationReponse"),
    path('modal/', modal, name="modal")
]

docollective/docollective/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from docollective import settings
from shop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("account/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("sav/", include("sav.urls")),
    path('verification/', include('verify_email.urls')),
]

if not settings.ENV == "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Docollective'
admin.site.site_title = "Docollective"

docollective/sav/urls.py
from django.urls import path

from .views import new_ticket, pending_tickets, closed_tickets, ticket_view, tickets_admin_view, close_ticket


app_name = "sav"
urlpatterns = [
    path("new-ticket/", new_ticket, name="new-ticket"),
    path("pending-tickets/", pending_tickets, name="pending-tickets"),
    path("closed-tickets/", closed_tickets, name="closed-tickets"),
    path("ticket/<int:pk>", ticket_view, name="ticket"),
    path("tickets-admin/", tickets_admin_view, name="admin-tickets"),
    path("close-ticket/<int:pk>/", close_ticket, name="close"),
]

docollective/shop/urls.py
from django.urls import path


from .views import detail_view, add_to_cart, cart_view, delete_garments_cart, delete_cart, CreateGarment, all_garments, \
    DeleteGarment, my_shop_view, validate_cart, address_choice_view, admin_deal_validation_view, recommendations_view, \
    admin_advert_validation_view

app_name = "shop"
urlpatterns = [
    path("garment/<str:slug>/<int:pk>/", detail_view, name="detail"),
    path("add-to-cart/<int:pk>/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("address-choice/", address_choice_view, name="address-choice"),
    path("validate-cart/", validate_cart, name="validate-cart"),
    path("delete-garments/", delete_garments_cart, name="delete-garments"),
    path("delete-cart/", delete_cart, name="delete-cart"),
    path("create-garment/", CreateGarment.as_view(), name="create"),
    path("delete-garment/<int:pk>/", DeleteGarment.as_view(), name="delete-garment"),
    path("all/", all_garments, name="all"),
    path("recommendations/", recommendations_view, name="recommendations"),
    path("my-shop/", my_shop_view, name="my-shop"),
    path("admin-validation/", admin_deal_validation_view, name="admin-validation"),
    path("admin-ad-validation/", admin_advert_validation_view, name="admin-advert"),


]

docollective/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/stylecalc.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/class-tools.js"></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/disable-element.js"></script>
</head>

<body>

<!--NOUVELLE BAR DE NAVIGATION-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-opacity-100">
<!--<nav class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark shadow">-->
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'index' %}">Calcul mental et automatismes</a>

        <!--Menu burger pour les smartphone-->
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-content"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-content">

        <!-- MENUS DE GAUCHE-->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

         <!-- MENU JOUER ET STATISTIQUES-->
          {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:jeu' %}">S'entraîner</a></li>
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:graphique' %}">Statistiques</a></li>
          {% endif %}
         <!-- FIN JOUER ET STATISTIQUES-->

         <!-- MENU TECHNIQUES-->
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown" data-bs-auto-close="outside">Techniques</a>
            <ul class="dropdown-menu shadow">
              <!--<li><a class="dropdown-item" href="#">Gallery</a></li>-->

              <li><a class="dropdown-item" href="#">Cerveau et Mémoires</a></li>
              <li><hr class="dropdown-divider"></li>
              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Automatismes</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href=""> Les Tables de Multiplication 0 ; 1 ; 2 ; 3 et 5</a></li>
                  <li><a class="dropdown-item" href=""> Les Tables de Multiplication 4 ; 6 ; 7 ; 8 et 9</a></li>
                </ul>
              </li>

              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Procédures niveau 1</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href="{% url 'shop:all' %}">Les additions</a></li>
                  <li><a class="dropdown-item" href="{% url 'shop:all' %}">Les soustractions</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 1</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 2</a></li>
                </ul>
              </li>

              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Procédures niveau 2</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href=""> Exemple 1</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 2</a></li>
                </ul>
              </li>

              <li class="dropend">
                <a href="#" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Procédures niveau 3</a>
                <ul class="dropdown-menu shadow">
                  <li><a class="dropdown-item" href=""> Exemple 1</a></li>
                  <li><a class="dropdown-item" href=""> Exemple 2</a></li>
                </ul>
              </li>
            </ul>
          </li>
         <!--FIN TECHNIQUES-->

         <!--NOUS CONTACTER -->
             <li class="nav-item dropdown">
                <a class="nav-link active dropdown-toggle" id="navbarDropdown30" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Nous Contacter</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown30">
                    <li><a class="dropdown-item" href="{% url 'sav:new-ticket' %}">Envoyer un message</a></li>
                    <li><hr class="dropdown-divider"/></li>
                    <li><a class="dropdown-item" href="{% url 'sav:pending-tickets' %}">Messages en cours</a></li>
                    <li><a class="dropdown-item" href="{% url 'sav:closed-tickets' %}">Historique</a></li>
                </ul>
            </li>
         <!-- FIN NOUS CONTACTER-->

        </ul>

        <!-- LIENS POUR ADMIN SEULEUMENT -->
                {% if request.user.is_superuser %}
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" id="navbarDropdown40" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Tâches en attente</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown40">
                        <li><a class="dropdown-item" href="{% url 'shop:admin-validation' %}">Echanges en attente</a></li>
                        <li><a class="dropdown-item" href="{% url 'shop:admin-advert' %}">Annonces en attente</a></li>
                        <li><a class="dropdown-item" href="{% url 'sav:admin-tickets' %}">Tickets en attente</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Administration</a></li>
                {% endif %}
        <!-- FIN LIENS ADMIN -->


        <!-- BARRE DE NAVIGATION DEUXIEME PARTIE A DROITE -->
            <ul class="navbar-nav  ml-auto mb-2 mb-lg-0 ms-lg-4 ml-auto">
                 <!-- Deconnexion Inscription Connexion-->
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:profile_eleve' %}">Profil</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Déconnexion</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Inscription</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Connexion</a></li>
                {% endif %}
                <!-- Fin Deconnexion Inscription Connexion-->
           </ul>
        <!-- FIN BARRE DE NAVIGATION A DROITE-->

      </div>
    </div>
  </nav>
<!-- FIN NOUVELLE BAR DE NAVIGATION-->




<!-- Header-->
<!--<header class="bg-light bg-gradient py-5 border border-secondary">-->
<header class="bg-light py-5">
    <div class="container px-4 px-lg-5 my-2">
        <div class="text-center text-black">
            <h1 class="display-4 fw-bolder text-color:primary text-primary opacity-50">Calcul mental et Automatismes</h1>
            <p class="lead fw-normal text-black-50 mb-0 text-secondary">Site pour s'entraîner et progresser</p>
        </div>
    </div>
</header>





<!--VIDEO -->
 <!-- <video id="video" autoplay loop muted>
    <source src="{% static 'assets/video1.mp4' %}" type="video/mp4" />
  </video>
  <div class="content">
    <h1 id="h1">Calcul mental et Automatismes</h1>
    <h2 id="h2">Site pour s'entraîner et progresser</h2>
  </div>
-->






<!-- Section-->

        {% block body %}
        {% endblock %}




<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>


<!-- FOOTER
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">Copyright &copy; Calcul Mental et Automatismes 2024</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
  <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
</svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
</svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
</svg></a></li>
    </ul>
  </footer>
</div>
-FOOTER-->

<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small class="text-white">Copyright &copy; Calcul Mental et Automatismes 2024</small>
    </div>
</footer>



</body>
</html>

docollective/templates/base_shop.html
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..."/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Fancy Product</h5>
                            <!-- Product price-->
                            $40.00 - $80.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>